# Generated by Django 3.2.5 on 2021-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210901_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=700, null=True, unique=True),
        ),
    ]
