# Generated by Django 2.2.6 on 2021-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211006_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='nonGroup', max_length=200, unique=True, verbose_name='Для URL-адреса'),
        ),
    ]
