# Generated by Django 2.2.6 on 2021-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211007_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='post',
            name='text_edit_post',
            field=models.TextField(default='Текст изменяемого поста', verbose_name='Текст изменяемого поста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Для URL-адреса'),
        ),
    ]
