# Generated by Django 2.2.6 on 2021-10-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211010_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_edit_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Текст нового поста', max_length=400, null=True, verbose_name='Текст поста'),
        ),
    ]
